// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CheckDark: typeof import('./src/components/CheckDark.vue')['default']
    GoTop: typeof import('./src/components/GoTop.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NSwitch: typeof import('naive-ui')['NSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCodeTheme: typeof import('./src/components/SelectCodeTheme.vue')['default']
  }
}
